### DISCUSSION TITLE
关于天赋/武器素材

### DISCUSSION THREAD

**Discussion by Xm798** [Arondight/Adachi-BOT#483] [Ideas]
改成现在的“今日素材”形式之后，不能像之前那样一览所有的素材了，而且武器没有名字感觉认起来还有一点不够直观（好像显得我有点像云玩家？hhh）经常有需要同时看好几个角色的素材，之前可以做到，现在做不到了。还有就是周日只会告诉全部开放，但也不知道该刷哪个子副本。
或许可以同时保留两个功能？

**Comment by Arondight** [comment]
米游社没有合适的图了，原来做图的那个人说工作很忙，说不定角色出了半个月才能作出图来，所以才换的。剩下的图一个都十几m根本不能用。

> 需要同时看好几个角色的素材
> 也不知道该刷哪个子副本

凑合一下用信息xxx看吧

**Reply by Xm798** [reply]
原来是这样 没有人接手嘛 不过他要是不给源文件的话重做一份确实也挺麻烦

**Reply by Arondight** [reply]
他还做，只不过没有时效性了

**Reply by mark9804** [reply]
> 剩下的图一个都十几m根本不能用

我有一个大胆的想法，这些图我们尝试手动压缩到3M左右，然后白嫖一个图床，之后就从图床请求这张压缩过后的图

> 武器没有名字

是可以加上的，前端当中有这个数据。虽然前端布局要重新写一下，现在的布局没考虑这个
![image](https://user-images.githubusercontent.com/9006264/145719748-b0b6078f-124a-4b06-89b5-cb60bb22d14c.png)

不过我觉得在最理想的状态下这个功能应该是能够完全自动生成图片的，因为我们的角色和武器 json 当中都有对应的角色需求素材，理论上我们可以只维护一个“秘境每日状态”的列表，而不是像现在这样需要手动添加“星期几应该刷什么武器/角色的材料”，现在的这个 `daily.yml` 长度之后会以很快的速度增长

例：
domains.yml

```yaml
塞西莉亚苗圃:
  - 水光之城:
    openDay: [ 'mon', 'thu', 'sun']
    materials: 
      - '高塔孤王的碎梦'
      - '高塔孤王的断片'
      - '高塔孤王的残垣'
      - '高塔孤王的破瓦'
  - 深没之谷:
    openDay: [ 'tue', 'fri', 'sun']
    materials: 
      - '凛风奔狼的怀乡'
      - '凛风奔狼的断牙'
      - '凛风奔狼的裂齿'
      - '凛风奔狼的始龀'
忘却之峡:
  - 霜凝祭坛:
    openDay: [ 'mon', 'thu', 'sun']
    materials: 
      - '「自由」的哲学'
      - '「自由」的指引'
      - '「自由」的教导'
  - 冰封废渊:
    openDay: [ 'tue', 'fri', 'sun']
    materials: 
      - '「抗争」的哲学'
      - '「抗争」的指引'
      - '「抗争」的教导'
```
在bot初始化的时候，遍历一遍武器和角色对应的 json 文件，对照上面的 `domains.yml` 生成一个素材字典维持在内存中，

```json
{
    "weapons": {
        "mon": {
            "水光之城":{
                "天空弓": ["素材1", "素材2", "素材3"],
                "天空枪": ["素材1", "素材2", "素材3"]
            }
        },
        "tue": {
            "水光之城":{
                "天空弓": ["素材1", "素材2", "素材3"],
                "天空枪": ["素材1", "素材2", "素材3"]
            }
        }
    },
    "talent": {
        "mon": {
            "忘却之峡": {
                "七七": ["素材1", "素材2", "素材3"],
            }
        },
        "tue": {}
    }
}
```

需要的时候直接从内存读取对应日期应该刷的东西返回
