### DISCUSSION TITLE
前端邪道

### DISCUSSION THREAD

**Discussion by mark9804** [Arondight/Adachi-BOT#715] [Ideas]
~~快别加新特性了，要跟不上了~~

<details>
<summary>Grid subgrid</summary>

<img src="https://user-images.githubusercontent.com/9006264/158228488-c5719cc7-1a6e-4dcf-9ec7-030e75400fc1.png" width="300" />
</details>

**Comment by mark9804** [comment]
```css
.parent {
    display: grid;
    /*等价于align-items和justify-items都设置为center*/
    place-items: center;
  }
```
