### ISSUE TITLE
去掉插件命令的硬编码，全部由配置文件控制

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#137]
现在 `commands.yml` 无法单独完成命令的控制，有很多地方是硬编码的

**Comment by Arondight** [comment]
```
plugin:
  function:
    - regex
```

这种形式似乎可以

**Comment by Arondight** [comment]
```
plugin:
  function:             # 功能代号
    command-string:     # 呈现给用户的功能命令
    usage-string:       # 呈现给用户的命令说明
    regex:
      - a               # 正则 a
      - b               # 正则 b
```

帮助信息对此进行拼接就可以了，分成 `command.yml` 和 `command_master.yml` 。

**Comment by Arondight** [comment]
```
gacha:
  gachaTenTimes:
    command-string: 十连
    usage-string:
    regex:
      - ^十连 *$
  change:
    command-string: 卡池 <角色 | 武器 | 常驻>
    usage-string: 切换【十连】的卡池
    regex:
      - ^卡池 +(常驻|角色|武器)
```

大约是这个感觉吧。

**Comment by Arondight** [comment]
```
plugin:
  enabled:
  functions:
    function:             # 功能代号
      command-string:     # 呈现给用户的功能命令
      usage-string:       # 呈现给用户的命令说明
      regex:
        - a               # 正则 a
        - b               # 正则 b
```

```
gacha:
  enabled: true
  functions:
    gachaTenTimes:
      command-string: 十连
      usage-string:
      regex:
        - ^十连 *$
    change:
      command-string: 卡池 <角色 | 武器 | 常驻>
      usage-string: 切换【十连】的卡池
      regex:
        - ^卡池 +(常驻|角色|武器)
```

**Comment by Arondight** [comment]
```
plugin:
  enable:
  regex:
    - abc               # 插件入口正则 a
    - bcd               # 插件入口正则 b
  functions:
    function:           # 功能代号
      command:          # 呈现给用户的功能命令
      usage:            # 呈现给用户的命令说明
      startswith:
        - a             # 功能入口 a
        - b             # 功能入口 b
```

```
plugin:
  enable: true
  regex:
    - - ^十连 *$
    - - ^(切换)?卡池 +(常驻|角色|武器)
  functions:
    gacha10:
      command: 十连
      usage:
      startswith:
        - 十连
    pool:
      command: 卡池 <角色 | 武器 | 常驻>
      usage: 切换【十连】的卡池
      startswith:
        - 卡池
	- 切换卡池
```

**Comment by Arondight** [comment]
差不多这个样子就可以了，为此需要把读 `.yml` 的 API 全部独立出去，读取后立刻转化为可操作性高的几个数据结构，然后增加对应的 API ，例如 `正则 -> 插件` 这种。

**Comment by Arondight** [comment]
提交 a05952bd0450f1d11c444e6dd70eb0160ea87ec0 已经把读 .yml 的 API 单独放到了一个文件。

**Comment by Arondight** [comment]
```
plugin:
  enable:
  regex:
    - abc               # 插件入口正则 a
    - bcd               # 插件入口正则 b
  functions:
    function:           # 功能代号
      name:             # 命令的名字
      usage:            # 呈现给用户的命令格式
      description:      # 呈现给用户的命令说明
      entrance:
        - a             # 功能入口 a
        - b             # 功能入口 b
```

```
gacha:
  enable: true
  regex:
    - ^十连 *$
    - ^(切换)?卡池 +(常驻|角色|武器)
  functions:
    gacha10:
      name: 十连
      usage: 十连
      description:
      entrance:
        - 十连
    pool:
      name: 卡池
      usage: 卡池 <角色 | 武器 | 常驻>
      description: 切换【十连】的卡池
      entrance:
        - 卡池
        - 切换卡池
```

**Comment by Arondight** [comment]
```
plugin:
  enable:               # 是否加载插件
  weights:              # 帮助信息里权重越高显示越靠前
  regex:
    - abc               # 插件入口正则 a
    - bcd               # 插件入口正则 b
  functions:
    function:           # 功能代号
      name:             # 命令的名字
      usage:            # 呈现给用户的命令格式
      description:      # 呈现给用户的命令说明
      entrance:
        - a             # 功能入口 a
        - b             # 功能入口 b
```

**Comment by Arondight** [comment]
```
plugin:
  enable:               # 是否加载插件
  weights:              # 帮助信息里权重越高显示越靠前
  regex:
    - abc               # 插件入口正则 a
    - bcd               # 插件入口正则 b
  functions:
    function:           # 功能代号
	  weights:          # 帮助信息里权重越高显示越靠前
      name:             # 命令的名字
      usage:            # 呈现给用户的命令格式
      description:      # 呈现给用户的命令说明
      entrance:
        - a             # 功能入口 a
        - b             # 功能入口 b
```

**Comment by Arondight** [comment]
```
aby:
  enable: true
  weights: 9699
  regex:
    - ^(上期)?深渊 *$
    - ^(上期)?深渊 +\d+.*$
    - ^(上期)?深渊 *\[CQ:at,qq=.*$
  functions:
    aby:
      weights: 9999
      name: 深渊
      usage: [游戏内UID、@群友]
      description:
      entrance:
        - 深渊
    lastaby:
      weights: 9899
      name: 上期深渊
      usage: [游戏内UID、@群友]
      description:
      entrance:
        - 上期深渊

artifacts:
  enable: true
  weights: 9299
  regex:
    - ^圣遗物 *$
    - ^圣遗物 +(\d+)$
    - ^(强化|副本) *$
  functions:
    artifacts:
      weights: 9999
      name: 圣遗物
      usage: [副本ID]
      description: 掉落一个圣遗物
      entrance:
        - 圣遗物
    strengthen:
      weights: 9899
      name: 强化
      usage:
      description: 强化掉落的上一个圣遗物
      entrance:
        - 强化

card:
  enable: true
  weights: 9899
  regex:
    - ^米游社 *$
    - ^米游社 +\d+.*$
    - ^米游社 *\[CQ:at,qq=.*$
  functions:
    card:
      weights: 9999
      name: 米游社
      usage: [米游社通行证ID、@群友]
      description: 查询并更新角色信息
      entrance:
        - 米游社

character:
  enable: true
  weights: 9599
  regex:
    - ^我的 +.+$
  functions:
    character:
      weights: 9999
      name: 我的
      usage: <角色名>
      description: 查询我的角色
      entrance:
        - 我的

gacha:
  enable: true
  weights: 9399
  regex:
    - ^十连 *$
    - ^卡池 +(常驻|角色|武器) *$
    - ^查看定轨 *$
    - ^取消定轨 *$
    - ^定轨 +.+$
    - ^定轨 *$
  functions:
    gacha:
      weights: 9999
      name: 十连
      usage:
      description:
      entrance:
        - 十连
    pool:
      weights: 9899
      name: 卡池
      usage: <常驻、角色、武器>
      description: 切换【十连】的卡池
      entrance:
        - 卡池
    select:
      weights: 9799
      name: 定轨
      usage: <武器名>
      description:
      entrance:
        - 定轨
    select-what:
      weights: 9699
      name: 查看定轨
      usage:
      description:
      entrance:
        - 查看定轨
    select-nothing:
      weights: 9599
      name: 取消定轨
      usage:
      description:
      entrance:
        - 取消定轨

tools:
  enable: true
  weights: 8699
  regex:
    - ^roll *([+-]?\d+)?$
    - ^help *$
    - ^带(个)?话 +.+$
    - ^管理 *$
  functions:
    roll:
      weights: 9999
      name: roll
      usage: [1-100]
      description: 掷骰子
      entrance:
        - roll
    feedback:
      weights: 9899
      name: 带话
      usage: <单行图文>
      description: 给主人带话
      entrance:
        - 带话
        - 带个话
    master:
      weights: 199
      name: 管理
      usage:
      description: 查看主人功能
      entrance:
        - 管理
    help:
      weights: 99
      name: help
      usage:
      description: 查看本帮助
      entrance:
        - help

material:
  enable: true
  weights: 9099
  regex:
    - ^武器 *$
    - ^天赋 *$
    - ^周本 *$
  functions:
    weapon:
      weights: 9999
      name: 武器
      usage:
      description: 武器素材表
      entrance:
        - 武器
    talent:
      weights: 9989
      name: 天赋
      usage:
      description: 天赋素材表
      entrance:
        - 天赋
    weekly:
      weights: 9979
      name: 周本
      usage:
      description: 周本材料表
      entrance:
        - 周本

menu:
  enable: true
  weights: 8899
  regex:
    - ^菜单 *$
    - ^(今天)?吃什么 *$
  functions:
    menu:
      weights: 9999
      name: 今天吃什么
      usage:
      description:
      entrance:
        - 今天吃什么
        - 吃什么
        - 菜单

music:
  enable: true
  weights: 8999
  regex:
    - ^点歌 +.+$
    - ^音乐源 +.+$
  functions:
    music:
      weights: 9999
      name: 点歌
      usage: <单行文本>
      description:
      entrance:
        - 点歌
    musicsource:
      weights: 9899
      name: 音乐源
      usage: <QQ、163>
      description: 切换【点歌】的音乐源
      entrance:
        - 音乐源

overview:
  enable: true
  weights: 9499
  regex:
    - ^(角色|武器|信息) +.+$
  functions:
    info:
      weights: 9999
      name: 信息
      usage: <角色名、武器名>
      description: 查询角色或武器的游戏数据
      entrance:
        - 信息
        - 角色  # 历史原因
        - 武器  # 历史原因

package:
  enable: true
  weights: 9799
  regex:
    - ^uid *$
    - ^uid +\d+.*$
    - ^uid *\[CQ:at,qq=.*$
  functions:
    package:
      weights: 9999
      name: uid
      usage: [游戏内UID、@群友]
      description: 查询并更新角色信息
      entrance:
        - uid

quote:
  enable: true
  weights: 8799
  regex:
    - ^伟大的升华 *$
  functions:
    quote:
      weights: 9999
      name: 伟大的升华
      usage:
      description:
      entrance:
        - 伟大的升华

rating:
  enable: true
  weights: 9199
  regex:
    - ^评分 *.+$ # https://github.com/Arondight/Adachi-BOT/issues/54
  functions:
    rating:
      weights: 9999
      name: 评分
      usage: <背包中的圣遗物截图>
      description:
      entrance:
        - 评分

save:
  enable: true
  weights: 9999
  regex:
    - ^(绑定|改绑) +\d+$
  functions:
    save:
      weights: 9999
      name: 绑定
      usage: <米游社通行证ID>
      description:
      entrance:
        - 绑定
    change:
      weights: 9899
      name: 改绑
      usage: <米游社通行证ID>
      description:
      entrance:
        - 改绑
```

**Comment by Arondight** [comment]
```
tools:
  enable: true
  weights: 9899
  regex:
    - ^回(个)?话 +\d+ +.+$
    - ^(好友|群)(广播|列表) +.+$
    - ^(查找|统计)列表 +.+$
    - ^系统(状态|信息) *$
  functions:
    reply:
      weights: 9999
      name: 回话
      usage: <QQ号、群号> <文本...>
      description:
      entrance:
        - 回话
        - 回个话
    group_boardcast:
      weights: 9899
      name: 群广播
      usage: <单行图文...>
      description:
      entrance:
        - 群广播
    private_boardcast:
      weights: 9799
      name: 好友广播
      usage: <单行图文...>
      description:
      entrance:
        - 好友广播
    group_search:
      weights: 9699
      name: 群列表
      usage:
      description: 查看所有群
      entrance:
        - 群列表
    private_search:
      weights: 9699
      name: 好友列表
      usage:
      description: 查看所有好友
      entrance:
        - 好友列表
    search:
      weights: 9599
      name: 查找列表
      usage: <关键字>
      description: 查找昵称、QQ号中包含关键字的好友和群
      entrance:
        - 查找列表

master:
  enable: true
  weights: 9999
  regex:
    - ^(带话|点歌|十连|圣遗物|评分|(游戏|官方)数据)权限 +\d+ +(on|off)$
    - ^响应消息 +\d+ +(on|off)$
    - ^刷新卡池 *$
  functions:
    feedback_auth:
      weights: 9999
      name: 带话权限
      usage: <QQ号、群号> <on、off>
      description: 【带话】
      entrance:
        - 带话权限
    music_auth:
      weights: 9899
      name: 点歌权限
      usage: <QQ号、群号> <on、off>
      description: 【点歌】
      entrance:
        - 点歌权限
    gacha_auth:
      weights: 9799
      name: 十连权限
      usage: <QQ号、群号> <on、off>
      description: 【十连】
      entrance:
        - 十连权限
    artifact_auth:
      weights: 9699
      name: 圣遗物权限
      usage: <QQ号、群号> <on、off>
      description: 【圣遗物】【强化】
      entrance:
        - 圣遗物权限
    rating_auth:
      weights: 9599
      name: 评分权限
      usage: <QQ号、群号> <on、off>
      description: 【评分】
      entrance:
        - 评分权限
    query_gameinfo_auth:
      weights: 9499
      name: 游戏数据权限
      usage: <QQ号、群号> <on、off>
      description: 【深渊】【上期深渊】【米游社】【uid】
      entrance:
        - 游戏数据权限
    character_overview_auth:
      weights: 9399
      name: 官方数据权限
      usage: <QQ号、群号> <on、off>
      description: 【角色】【武器】
      entrance:
        - 官方数据权限
    reply_auth:
      weights: 9299
      name: 响应消息
      usage: <QQ号、群号> <on、off>
      description:
      entrance:
        - 响应消息
    refresh_wish_detail:
      weights: 9199
      name: 刷新卡池
      usage:
      description:
      entrance:
        - 刷新卡池
```
