### ISSUE TITLE
【bug？】管理命令的执行优先度低于普通命令

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#170]
#164 中引入的bug，会优先执行普通命令，然后再执行管理命令

**Comment by Mark9804** [comment]
手快enter了，详细说明一下。

在旧版本的`command.yml`中，命令执行的顺序是文件中该命令的出现顺序。管理命令在这些命令当中还算靠前，我又喜欢在文件末尾添加自己的更改，当时我就没有发现。

#164 之后，程序的命令执行逻辑似乎已经完全变成了“先遍历`command.yml`中的命令”→“再遍历`command-master.yml`中的命令”，优先级顺序可能要调整一下。一般任何时候管理的命令优先级都应该大于用户优先级。

**Comment by Arondight** [comment]
不应该有优先级，命令之间有任何覆盖都是不合逻辑的，尽量不要起同名的命令吧

**Comment by Arondight** [comment]
另外我注意到你的功能入口写了正则，实际上……

1. 这里只是一个 startsWith 判断，改成正则不要忘记修改一下对应的方法
2. 很多插件并没有判断功能入口，只匹配了插件入口的正则

**Comment by Mark9804** [comment]
了解了，就是说这个功能入口理论上可以留空，或者说功能理论上都可以不写？

例：
```yaml
menu:  # 今天吃什么
  enable: true
  weights: 8899
  regex:
    - ^菜单 *$
    - ^(今[天晚个儿]{0,2})?([早晚][上饭餐]?|中午|午[饭餐])?吃(什么|[啥嘛]) *[\?？]?$
 
music:
  enable: true
  …
```
