### ISSUE TITLE
增加命令类型，把配置文件的硬编码集中到代码里，对用户隐藏

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#235]
```
type: command
type: option
```

```
is_command: true
is_option: true
```

我更倾向后者，但是前一种代码写起来不啰嗦

**Comment by Arondight** [comment]
管理命令类型叫 switch 好一点，option 是个多选一，switch 是个开关

**Comment by Arondight** [comment]
```
type: command
type: switch
type: option
options:
  name1: 名字A
  name2: 名字B
```
