### ISSUE TITLE
所有类型为 switch 的功能全部转化为 option

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#242]
```
type: switch
```

内部转换为下面的结构。

```
type: option
options:
  on: on
  off: off
```

从此转换后的数据结构中， `type` 不再有可能为 `switch` ，逻辑处理起来更加统一和简单，这是一件好事。

---

目的是把所有的硬编码集中到一处，下面的硬编码 `on` 集中到 `config.js` 的数据转换逻辑中。

https://github.com/Arondight/Adachi-BOT/blob/7d1e29eaf330b9cf3201f5344bd44fbcfdbd4677/src/plugins/master/index.js#L7

这样一来，所有的硬编码全部集中到了一起，这是一件好事。
