### ISSUE TITLE
如何获得滑动验证码 ticket

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#310]
现已支持扫码登录，推荐在 [setting.yml](config_defaults/setting.yml) 中使用扫码登录，避免出现 ticket 验证。

```yaml
accounts:
  -
    qq: 123456789
    password: null
    platform: 5
```

---

你有两种方式：

1. （推荐）使用 [TxCaptchaHelper](https://github.com/mzdluo123/TxCaptchaHelper) ，在[这里](https://github.com/mzdluo123/TxCaptchaHelper/releases)下载 apk ，安装到安卓手机上。复制给出的链接地址，在“滑动验证助手” APP 中进行验证，即可得到需要的 ticket ，这种方法可以模拟真机滑动，有效降低登录异常 237 的概率。
2. 访问给出的链接地址，然后浏览器中使用开发者模式，手动拿到验证请求中返回的 ticket 。

随后粘贴 ticket 文本到终端，按下回车键。
