### ISSUE TITLE
简单的 qa 列表

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#865]
### 问题描述

我想搞个功能，配置文件里面写正则匹配，然后回一段文字或者图片

```
settings:
  -
    match: [ "猫{1,2}图$" ]
    reply:
      type: image
      path: "../猫.png"
```

### 当前提交

```Text
?
```
